EXTERIOR_LENGTH = 255
EXTERIOR_WIDTH = 210
EXTERIOR_HEIGHT = 30

M3_THREADED_INSERT_DIAMETER = 5
M3_THREADED_INSERT_HEIGHT = 6

KEYBOARD_LENGTH = 230
KEYBOARD_WIDTH = 78
KEYBOARD_CASE_BOTTOM_WALL_THICKNESS = 5
KEYBOARD_CASE_POSTS_HEIGHT = 10
KEYBOARD_CASE_POSTS_DIAMETER = M3_THREADED_INSERT_DIAMETER + 4

TOLERANCE = 0.3